language: php

php:
    - 7.3
    - 7.2
    - 7.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/bin/atoum
