language: php

php:
    - 7.3
    - 7.2
    - 7.1
    - nightly

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.1
          env: SYMFONY_VERSION=2.8.*
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=4.3.*
        - php: 7.1
          env: SYMFONY_VERSION=4.4.*@dev
    allow_failures:
        - php: nightly
        - php: 7.1
          env: SYMFONY_VERSION=4.4.*@dev

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/bin/atoum
